#! /bin/bash
while :
do
    # Read Temperature
    tempread=`cat /sys/bus/w1/devices/28-0316a2797668/w1_slave`
    # Format
    temp=`echo "scale=2; "\`echo ${tempread##*=}\`" / 1000" | bc`
    
    # Output
    echo "The measured temperature is " $temp "°C"
done